### ISSUE TITLE
push notifications status returns null

### ISSUE THREAD

**Issue by KixS** [driftyco/ionic-cloud#42]
Hi,

I'm struggling to get the push notifications to work on iOS. While on Android it works just fine.
I've been getting ILLEGAL_CREDENTIAL_FORMAT errors which were due to me not setting up correctly the profiles. 

However at some point I succeeded to get the right configuration as I was getting APNS_DEVICE_TOKEN_NOT_FOR_TOPIC;

After some other attempts I got: APNS_BAD_DEVICE_TOKEN

After that whatever the configuration I try, I get an empty push notification status.
Below an example where I send a push notification to only one iOS device and the answer I get.

Request
```
data:
   app_id: "c04b033e"
   config:
     tokens:
        0:"3ed0b038d9a185a9f6d6f18420a3be21f55b4311c05a078fbf7a96969ad8c264"
   created:"2016-09-01T11:04:53.607264+00:00"
   state: "enqueued"
   status: "open"
   uuid: "1bfa66ac-2ee1-4d2a-b0c0-2ec16084a188"

meta:
  request_id: "5d3442d6-8197-4ab9-aab7-7c3c4175d8d0"
  status: 201
  version: "2.0.0-beta.0"
```
Answer
```
{
    "data": [],
    "meta": {
        "request_id": "932d420f-40b6-4a8c-bdd8-6ed904f5c21e",
        "status"    : 200,
        "version"   : "2.0.0-beta.0"
    }
}
```

Any idea why I don't get any status anymore while I do send the push ?
